"""Data models and configuration for person detection inference."""

from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class PersonDetection:
    """Represents a single person detection generated by a model inference pass."""
    frame_index: int
    bb_left: float
    bb_top: float
    bb_width: float
    bb_height: float
    confidence: float
    class_name: str = "person"

    @property
    def bbox_xywh(self) -> Tuple[float, float, float, float]:
        """Bounding box in (left, top, width, height) format."""
        return self.bb_left, self.bb_top, self.bb_width, self.bb_height

    @property
    def bbox_xyxy(self) -> Tuple[float, float, float, float]:
        """Bounding box in (x1, y1, x2, y2) format."""
        return self.bb_left, self.bb_top, self.bb_left + self.bb_width, self.bb_top + self.bb_height

    @property
    def area(self) -> float:
        """Bounding box area in pixels."""
        return max(0.0, self.bb_width) * max(0.0, self.bb_height)


@dataclass(frozen=True)
class DetectionConfig:
    """Configuration options for person detectors."""
    confidence_threshold: float = 0.5
    iou_threshold: float = 0.5
    model_name: str = "yolov8n.pt"
    device: str = "cpu"
